server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    web: debug
