name: add-env

on:
  push:
    branches:
      - add-env

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: test
        run: |
          pwd
          echo "${{ secrets.NEW_ENV }}" > new_env