name: deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: setup JDK 17 corretto
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradle build
        run: |
          cd util
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Extract JAR file name
        id: extract_jar
        run: |
          echo "JAR_FILE=$(ls util/build/libs/*.jar)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker buildx build ./ \
          --platform=linux/amd64 \
          --build-arg JAR_FILE=$JAR_FILE \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_SPRING_REPOSITORY }}:latest 

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_SPRING_REPOSITORY }}:latest

  deploy:
    needs: build-and-push-docker-image
    runs-on: self-hosted
    steps:
      - name: chown runner
        run: |
          sudo chown -R ubuntu:ubuntu ~/actions-runner

      - name: grant permission to execute deploy script
        run: |
          chmod +x ./deploy.sh

      - name: run deploy script
        run: |
          sh ./deploy.sh
      
      

