name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: run docker-compose
        run: |
          docker-compose -f ~/actions-runner/docker-compose.yml up -d
